# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "end.re"
license = "CC4-BY-SA"
licenselink = "https://github.com/endreszabo/hugo-theme-end.re/blob/master/LICENSE.md"
description = "A simple theme with parts shamelessly stolen from a variety of themes"
homepage = "https://github.com/endreszabo/blog/theme/end.re"
tags = ["blog", "minimal"]
features = ["blog", ""]
min_version = 0.20

[author]
  name = "Endre Szabo"
  homepage = "https://github.com/endreszabo/hugo-theme-end.re"

# If porting an existing theme
[original]
  name = "Minos"
  homepage = "https://github.com/carsonip/hugo-theme-minos"
  repo = "https://github.com/carsonip/hugo-theme-minos"
